const userTypes = {
  SIGN_UP_USER_START: "SIGN_UP_USER_START",

  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIGN_OUT_USER_START: "SIGN_OUT_USER_START",
  SIGN_OUT_USER_SUCCESS: "SIGN_OUT_USER_SUCCESS",
  RESET_PASSWORD_START: "RESET_PASSWORD_START",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  USER_ERRORS: "USER_ERRORS",

  ADD_NEW_DATA_START: "ADD_NEW_DATA_START",
  FETCH_USERS_START: "FETCH_USERS_START",
  SET_USERS: "SET_USERS",

  FETCH_USER_START: "FETCH_USER_START",
  SET_USER: "SET_USER",

  UPDATE_USER_DATA: "UPDATE_USER_DATA",
  // SET_CURRENT_USER: "SET_CURRENT_USER",
  // RESET_AUTH_FORMS: "RESET_AUTH_FORMS",
};

export default userTypes;
