const weekTrainingTypes = {
  ADD_NEW_TRAINING_SCHEDULE: "ADD_NEW_TRAINING_SCHEDULE",

  FETCH_TRAINING_SCHEDULES_START: "FETCH_TRAINING_SCHEDULES_START",
  SET_TRAINING_SCHEDULES: "SET_TRAINING_SCHEDULES",

  FETCH_USER_TRAINING_SCHEDULE: "FETCH_USER_TRAINING_SCHEDULE",
  SET_USER_TRAINING_SCHEDULE: "SET_USER_TRAINING_SCHEDULE",

  ADD_NEW_TRAINING_WEEK_START: "ADD_NEW_TRAINING_WEEK_START",

  FETCH_USER_TRAINING_WEEKS_START: "FETCH_USER_TRAINING_WEEKS_START",
  SET_USER_TRAINING_WEEKS: "SET_USER_TRAINING_WEEKS",

  GO_BACK_USERS_START: "GO_BACK_USERS_START",

  UPDATE_USER_REMINDER: "UPDATE_USER_REMINDER",
  UPDATE_USER_SHOW_HIDE: "UPDATE_USER_SHOW_HIDE",

  DELETE_EXERCISE_START: "DELETE_EXERCISE_START",
};

export default weekTrainingTypes;
