const calendarTrackerTypes = {
  ADD_NEW_CALENDAR: "ADD_NEW_CALENDAR",
  ADD_NEW_DAY: "ADD_NEW_DAY",

  FETCH_CALENDARS_START: "FETCH_CALENDARS_START",
  SET_CALENDARS: "SET_CALENDARS",

  FETCH_USER_CALENDAR: "FETCH_USER_CALENDAR",
  SET_USER_CALENDAR: "SET_USER_CALENDAR",

  ADD_NEW_CALENDAR_DAY_START: "ADD_NEW_CALENDAR_DAY_START",
  ADD_NEW_CALENDAR_DAY: "ADD_NEW_CALENDAR_DAY",

  FETCH_USER_CALENDAR_DAYS_START: "FETCH_USER_CALENDAR_DAYS_START",
  SET_USER_CALENDAR_DAYS: "SET_USER_CALENDAR_DAYS",

  // DELETE_DAY_START: "DELETE_DAY_START",
};

export default calendarTrackerTypes;
