const exerciseTypes = {
  ADD_NEW_EXERCISE: "ADD_NEW_EXERCISE",
  FETCH_EXERCISES_START: "FETCH_EXERCISES_START",
  SET_EXERCISES: "SET_EXERCISES",
  DELETE_EXERCISE_START: "DELETE_EXERCISE_START",
};

export default exerciseTypes;
